# -*- coding: utf-8 -*-
"""rock_paper_scissors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cuRe06fOIDUlO0dXoV6Gwl3gb9K7SalE
"""

#Import the random library
import random

#Add the code to create a list containing the three actions of the game.
game_actions = ["rock", "paper", "scissors"]

#Add the code to set the scores of players to 0
p1_score = 0
p2_score = 0

#Add the code to ask the user how many rounds they want to play
rounds = int(input("how many times? "))
count = 1
#Write a for loop and put the game inside
while count <= rounds:
  #Add the code to select a random action for each player
  p1 = random.choice(game_actions)
  p2 = random.choice(game_actions)
  #Add the code to print the players choices
  print(count,":",p1,p2)

  #Add the tie condition
  if p1 == p2:
    print("Its a Tie")
    p1_score +=1
    p2_score +=1
    count +=1
  #Add the remaining condition
  elif p1 == "rock" and p2 == "paper" or p1 == "paper" and p2 == "scissors" or p1 == "scissors" and p2 == "rock":
    print("p2 is the winner")
    p2_score +=1
    count +=1
  elif p1 == "paper" and p2 == "rock" or p1 == "scissors" and p2 == "paper" or p1 == "rock" and p2 == "scissors":
    print("p1 is the winner")
    p1_score +=1
    count +=1
  #print the score

print("p1 score:",p1_score,"p2 score:", p2_score)